version: '3'
services:
  api:
    build:
      context: ./docker/ #path to docker file
      dockerfile: .dockerfileApi
    env_file:
      - .env
    volumes:
      - ./:/usr/share/nginx/api:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
      - laravel_echo_server
  app:
    build:
      context: . #path to docker file
      dockerfile: docker/.dockerfileApp
    command: sh -c "npm install && npm run serve" # serve for develop environment only
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules/
    environment:
      HOST: 0.0.0.0
  http-nginx:
    image: nginx:1.14.2-alpine
    ports:
      - "8087:80"
      - "443:443"
    volumes:
      - ./docker/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/usr/share/nginx/api:cached
    links:
      - app
      - api
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: elearning
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
  laravel_echo_server:
    build:
      context: ./docker/laravel-echo-server/
      dockerfile: .dockerfileLC
    volumes:
      - .env:/app/.env
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - ./docker/data/redis:/data
    restart: unless-stopped
